app_vector: main.o vector3d.o point3d.o 
		g++ main.o vector3d.o point3d.o -c app_vector
	main.o: main.cpp
		g++ main.cpp -c main.o
	vector3d.o: vector3d.cpp
		g++ vector3d.cpp -c vector3d.o
	point3d.o:	point3d.cpp
		g++ point3d.cpp -c point3d.o
